[package]
name = "oxbow"
version = "0.6.1"
edition = "2021"
keywords = ["deltalake", "parquet", "lambda", "delta"]
homepage = "https://github.com/buoyant-data/oxbow"
repository = "https://github.com/buoyant-data/oxbow"
description = "Tooling for converting directories of Apache Parquet files into Delta Lake tables"
license-file = "LICENSE.txt"

[[bin]]
name = "oxbow-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "oxbow-lambda"
path = "src/bin/lambda.rs"

[dependencies]
anyhow = "=1"
chrono = "0.4.31"
deltalake = { version = "0.16.4", features = ["s3", "json"]}
futures = "0.3.29"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter", "tracing-log"] }
tokio = { version = "=1", features = ["macros"] }
url = { version = "2.3", features = ["serde"] }

# cli requirements
gumdrop = "=0.8"

# lambda requirements
aws_lambda_events = { version = "0.10.0", default-features = false, features = ["s3", "sqs"]}
dynamodb_lock = { version = "0.6.0" }
lambda_runtime = { version = "0.8" }
rusoto_core = { version = "0.47", default-features = false, features = ["rustls"]}
rusoto_credential = { version = "0.47"}
rusoto_s3 = { version = "0.47", default-features = false, features = ["rustls"] }
serde = { version = "=1", features = ["rc"] }
serde_json = "=1"
urlencoding = "=2"

[dev-dependencies]
fs_extra = "=1"
tempfile = "*"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

